
#pragma once
typedef enum {
  EN_FUNCMODE_HOME = 0,
  EN_FUNCMODE_TALLY,
  EN_FUNCMODE_SWITCH,
  EN_FUNCMODE_SETUP,
  EN_FUNCMODE_MAX
} EN_FUNCMODE;
typedef enum {
  EN_BLACK = 0,
  EN_CAM1,
  EN_CAM2,
  EN_CAM3,
  EN_CAM4,
  EN_CAM_MAX
} EN_CAMNUM;

typedef enum {
  EN_SETUP_DEVICEID = 0,
  EN_SETUP_SSID,
  EN_SETUP_PASSWORD,
  EN_SETUP_ATEMIP,
  EN_SETUP_AUTOSWITCHTIME
} EN_SETUPWIZARD_STEP;
typedef enum {
  EN_SETTING_UNITID,
  EN_SETTING_SSID,
  EN_SETTING_PASS,
  EN_SETTING_IPADDRESS,
  EN_SETTING_ATEM_IP,
  EN_SETTING_BRIGHTNESS,
  EN_SETTING_CAMNUM,
  EN_SETTING_MAX,
} EN_SETTINGMENU;

typedef enum {
  EN_KEY_UP,
  EN_KEY_DOWN,
  EN_KEY_BACKSPACE,
  EN_KEY_ENTER
} EN_KEYBOARD_OPERATION;

typedef enum{
    EN_UNKNOWN,
    EN_BATTERY,
    EN_CHARGING,
    EN_CHARGED,
    EN_CHG_STATE_MAX,
}EN_CHG_STATE;
